### ISSUE TITLE
Incorrect parameter names in LinksetData functions

### ISSUE THREAD

**Issue by TedHankey** [Sei-Lisa/kwdb#2]
Some of the LinksetData functions have incorrect parameter names in the kwdb. Some, like 'string key' are invalid syntax as well.
According to the SL wiki, they should be as follows:

linkset_data(integer action, string ***name***, string value)
integer llLinksetDataDelete(string ***name***)
integer llLinksetDataDeleteProtected(string ***name***, string ***pass***)
string llLinksetDataRead(string ***name***)
string llLinksetDataReadProtected(string ***name***, string ***pass***)
integer llLinksetDataWrite(string ***name***, string value)
integer llLinksetDataWriteProtected(string ***name***, string value, string ***pass***)

**Comment by Sei-Lisa** [comment]
Good point about the invalid syntax, but I'd like to know if you need the identifiers to match those of the SL wiki, and why. These identifiers are never reflected in actual LSL code in any way; their only purpose is to give hints about what the parameters mean, in places where there's documentation for the function, as well as for the signature to resemble that of a user-defined function.

For that reason, I'm inclined to rename "key" as "keyname" rather than "name", as that implies that it's the name of a key in a key/value pair. So. I'd like to hear your reasoning for following the SL wiki naming. These are not the only functions that don't follow the wiki (or the sim-provided LLSD keywords file).

**Comment by TedHankey** [comment]
I have no need for them to be the same at all. I just saw many names that do follow the wiki and therefore assumed that was your intention. Since you made it clear that isn't the case, the only issue left then is the invalid syntax.

**Comment by Sei-Lisa** [comment]
Alright then, I've pushed a fix. Thank you very much for reporting.
